import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'
import useTranslation from 'next-translate/useTranslation';
import { Stack, Button } from '@mui/material'
import magnifier from '../public/magnifier.svg';
import man from '../public/man.png';
import fromCaradle from '../public/fromCradle.svg';

const Home: NextPage = () => {

  const { t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>Agiler</title>
        <meta name="description" content="Generated by create next app" />npm run
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <a href="https://nextjs.org/docs" className={styles.}><Image src={fromCaradle} alt='Agiler' width={200} height={48}></Image></a>
        <a href="https://nextjs.org/docs"><Image src={magnifier} alt='Magnifier' width={24} height={24}></Image></a>
        <a href="https://nextjs.org/docs"><Image src={man} alt='Man' width={48} height={48}></Image></a>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Make Your <a href="https://nextjs.org">Agile!</a>
        </h1>

        <Stack spacing={2} direction="row">
          <Button variant="text">Text</Button>
          <Button variant="contained">Contained</Button>
          <Button variant="outlined">Outlined</Button>
        </Stack>

        <h2>{t('common:Japanese')}</h2>
        <h2>{t('common:English')}</h2>
        <h2>{t('common:Korean')}</h2>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
